### ISSUE TITLE
How to import data structures defined "elsewhere", i.e. by other organizations ?

### ISSUE THREAD

**Issue by Denisthemalice** [transmute-industries/ietf-spice-charter#10]
There was no comment on my comment sent last week under the issue #3:

> How to import data structures defined "elsewhere", i.e. by other organizations.

"Standard claims" have been registered by the IANA as "JSON Web Token Claims". 
See: https://www.iana.org/assignments/jwt/jwt.xhtml

However, some other claims used in some sectors (e.g. healthcare) or some professional use cases, will need to be defined "elsewhere" and may even be country specific.

What would be the best way to be able to import them into a schema ?

**Comment by hannestschofenig** [comment]
There are various ways to do this. For example, claims could be defined by other organizations and then registered with IANA.
This is how the OpenID Foundation approached it.  The barrier of entry is very low since only a "specification" is required to register a claim in that registry.

So, I don't see the problem.

**Comment by Denisthemalice** [comment]
I do know that OpenID has registered with IANA useful attributes that are relevant for identity documents. 

When using IANA registry,  programmers expect to be able to click on a URL that provides the details. It should be noticed that ISO standards are usually not free of charge and hence are not freely accessible. Hence, it is not possible to get any details that are in the core of an ISO standard. 

The barrier of entry is not so low, since ISO standards will not be able to use the IANA registry.

On the contrary, ETSI standards (which are freely accessible) are able to use a standard mechanism using ETSI-based URIs.

W3C is using JSON-LD that does not require using the IANA registry, but URIs.

A JSON schema can also include a pointer to point to another JSON (external) schema.

Looking at the problem not from the solution, but from the problem, the idea is to allow "vertical sectors" (e.g., healthcare, education) in different countries to define their own claims, in addition to the already-registered IANA useful attributes that are relevant for usual identity documents.
