### ISSUE TITLE
Possible working group names

### ISSUE THREAD

**Issue by OR13** [transmute-industries/ietf-spice-charter#30]
- Secure Patterns for Internet CrEdentials (current name)
- Scalable Portable Internet Credential Extensions
- Scalable Portable Identity Credential Extensions
- ConciSe Profiles for Identity Credentials

More inspiration from RFC4949:

> A public-key certificate may be used as an "identity credential", and an attribute certificate may be used as an "authorization credential".

Replace the word "certificate" with COSE or JOSE envelope, and the rest of this matches up 100%, in my view.

**Comment by mprorock** [comment]
Don't see any particular strong reason to adjust the name.  If folks felt strongly about swapping "internet" for "identity" I wouldn't block it, but credentials deal with more than identity

**Comment by selfissued** [comment]
I’d prefer that we keep the term “Digital Credentials”.  It’s already in widespread use with this meaning.  For instance, it’s used in the name of the [OpenID Digital Credentials Working Group](https://openid.net/wg/digital-credentials-protocols/).  Inventing another name will only have the effect described in https://xkcd.com/927/.

Yes, naming is hard.
